CREATE TABLE `interests` (
`uname` varchar(100) NOT NULL,
`c1` varchar(3) DEFAULT 'no',
`c2` varchar(3) DEFAULT 'no',
`c3` varchar(3) DEFAULT 'no',
`c4` varchar(3) DEFAULT 'no',
`c5` varchar(3) DEFAULT 'no',
`c6` varchar(3) DEFAULT 'no',
`c7` varchar(3) DEFAULT 'no',
`c8` varchar(3) DEFAULT 'no',
`c9` varchar(3) DEFAULT 'no',
`c10` varchar(3) DEFAULT 'no',
`c11` varchar(3) DEFAULT 'no',
`c12` varchar(3) DEFAULT 'no',
`c13` varchar(3) DEFAULT 'no',
`c14` varchar(3) DEFAULT 'no',
`c15` varchar(3) DEFAULT 'no',
`d1` varchar(3) DEFAULT 'no',
`d2` varchar(3) DEFAULT 'no',
`d3` varchar(3) DEFAULT 'no',
`e1` varchar(3) DEFAULT 'no',
`e2` varchar(3) DEFAULT 'no',
`e3` varchar(3) DEFAULT 'no',
PRIMARY KEY (`uname`)
);
